### ISSUE TITLE
Dataset link is broken

### ISSUE THREAD

**Issue by ForrestPi** [Dancingmader/3D-High-quality-Garment-Dataset#1]
Hi，
the dataset link is broken. 
could you please update the link?

**Comment by Dancingmader** [comment]
Hi, sorry for the issue. The link has been updated.

**Comment by ForrestPi** [comment]
@Dancingmader  Thanks.
will you plan to release the code?

**Comment by Dancingmader** [comment]
Sorry, we have no plans to release the code so far.
